### ISSUE TITLE
2020 Weekly Data Formatting

### ISSUE THREAD

**Issue by Smellfuzz** [fantasydatapros/data#8]
Hello, the 2020 data is formatted differently than the rest of the 1999 - 2019 data. It has differential columns and excludes some. Can we get a 2020 weekly pull in same format for database integrity?

**Comment by srtalaie** [comment]
Specifically 'snapcount' to 'offensive_snapcount' for now. I think that is the biggest difference between the Machine Learning - Regression course section data set and the 2020 weekly data.

**Comment by Smellfuzz** [comment]
It is only occuring in 2009 and 2004 in week 17 each as well, not sure if
that helps. Thank you!

**Comment by fantasydatapros** [comment]
Noted - working on fixing column names now.

**Comment by fantasydatapros** [comment]
2020 weekly data has been reformatted. Snap count data is now being held in a separate CSV file which is linked in the regression section of the course (also no need to merge this data with the old data_cleaned.csv file anymore with the new CSV file).
